# Site settings
author: Bak Miah
title: Building ruby CLI project
header-img: img/home-bg.png
email: baktiar.m@gmail.com
copyright_name: Bak Miah
description: > # this means to ignore newlines until "baseurl:"
  Scraping data 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  baktiarm1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
